version: '3.8'
services:
  db:
    image: postgres:16-alpine
    container_name: cake-suite-db
    environment:
      POSTGRES_DB: cake-suite
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d cake-suite"]
      interval: 5s
      timeout: 5s
      retries: 10
volumes:
  db_data:
