version: '3.8'
services:
  mongodb:
    image: mongo:6.0
    container_name: cake-suite-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: cake-suite
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/cake-suite --quiet
      interval: 5s
      timeout: 5s
      retries: 10
volumes:
  mongodb_data:
